openapi: 3.1.0
info:
  description: |
    This is API Specification for Repair Management System to handle the repair flow of electronics repair shop.
  version: 0.0.1
  title: Repair Management System | RMS
  # termsOfService: 'http://rms.merazmi.com/terms/'
  # contact:
  #   email: apiteam@swagger.io
  # license:
  #   name: Apache 2.0
  #   url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'https://rms-devapi.merazmi.com/api/v1'
    description: "Version 1"
paths:
  /repairs:
    get:
      summary: List all repair requests
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
