openapi: 3.0.3
info:
  title: Tenant Service API
  version: 1.0.0
paths:
  /tenants:
    get:
      summary: List tenants
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tenant'

components:
  schemas:
    Tenant:
      type: object
      allOf:
        - $ref: './shared-spec.yaml#/components/schemas/AuditFields'
        - type: object
          properties:
            id: { type: string, format: uuid }
            name: { type: string }
            homeAddress:
              $ref: './shared-spec.yaml#/components/schemas/Address'
